require: rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - 'analist.gemspec'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'lib/analist/annotator.rb'
    - 'lib/analist/checker.rb'
    - 'lib/analist/cli.rb'

Style/Documentation:
  Enabled: false
