require: rubocop-rspec

AllCops:
  Exclude:
    - 'example.rb'
    - 'vendor/**/*'
    - 'spec/support/**/*'

Metrics/AbcSize:
  Exclude:
    - 'lib/analist/annotations.rb'
    - 'lib/analist/annotator.rb'
    - 'lib/analist/checker.rb'
    - 'lib/analist/errors.rb'

Metrics/BlockLength:
  Exclude:
    - 'analist.gemspec'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'lib/analist/annotator.rb'
    - 'lib/analist/checker.rb'
    - 'lib/analist/cli.rb'
    - 'lib/analist/explorer.rb'
    - 'lib/analist/errors.rb'
    - 'lib/analist/headerizer.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/analist/annotator.rb'

Style/Documentation:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
